// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3DaDluGHALIdYKurqWGWjWCZJUR-303M',
    appId: '1:766764091598:web:197a3d742c145a6d59289f',
    messagingSenderId: '766764091598',
    projectId: 'hackbangalore',
    authDomain: 'hackbangalore.firebaseapp.com',
    storageBucket: 'hackbangalore.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Z81h7ZHRpZ-IQYcIA4vvsKe2W0nBy9M',
    appId: '1:766764091598:android:8ac11602edc6e81e59289f',
    messagingSenderId: '766764091598',
    projectId: 'hackbangalore',
    storageBucket: 'hackbangalore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBw1hzh37Y5bpjzfreFQNm9U88nuZ8jVg',
    appId: '1:766764091598:ios:945292f681f539f459289f',
    messagingSenderId: '766764091598',
    projectId: 'hackbangalore',
    storageBucket: 'hackbangalore.appspot.com',
    iosBundleId: 'com.example.client',
  );
}
